---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma.git
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.7"
    hooks:
      - id: ruff
        args:
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/pycqa/pylint.git
    rev: v3.3.0
    hooks:
      - id: pylint
        args: ["--ignore-paths=tests/"]
        additional_dependencies:
          - jinja2
          - typer
          - pyyaml
          - ruamel.yaml

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.11.2
    hooks:
      - id: mypy
